In [1]:
import numpy as np
import time
import pandas as pd

In [2]:
a = np.random.random((10,10))

In [3]:
a

array([[0.47949963, 0.7299345 , 0.90773463, 0.84141837, 0.867988  ,
        0.31235114, 0.90253769, 0.36608185, 0.7321836 , 0.57726822],
       [0.21516325, 0.57756153, 0.89818507, 0.81995957, 0.35060484,
        0.82970734, 0.46323527, 0.32227353, 0.44831145, 0.83305571],
       [0.00731276, 0.47727155, 0.81572745, 0.93915316, 0.30892678,
        0.6533983 , 0.37823214, 0.22721625, 0.94567981, 0.84548707],
       [0.83454918, 0.59649341, 0.79014112, 0.46593649, 0.3621356 ,
        0.8649656 , 0.72665958, 0.06282294, 0.36523932, 0.98355808],
       [0.7662607 , 0.61106074, 0.61188846, 0.98941861, 0.52545861,
        0.56110447, 0.23778176, 0.73713815, 0.6909835 , 0.70079236],
       [0.87581321, 0.33501248, 0.62943106, 0.77447654, 0.78880335,
        0.92721142, 0.83887853, 0.31346104, 0.05256299, 0.15068996],
       [0.06310261, 0.74676515, 0.25485637, 0.55354778, 0.90621103,
        0.03757763, 0.01284579, 0.38834101, 0.16925152, 0.02201443],
       [0.62583233, 0.43006473, 0.4510735

In [4]:
start = time.time()

In [5]:
for x in range(10):
    for y in range(10):
        a[x][y] = a[x][y] +10

In [6]:
end = time.time()

In [7]:
time_taken = end - start

In [8]:
time_taken

0.03108048439025879

In [9]:
a

array([[10.47949963, 10.7299345 , 10.90773463, 10.84141837, 10.867988  ,
        10.31235114, 10.90253769, 10.36608185, 10.7321836 , 10.57726822],
       [10.21516325, 10.57756153, 10.89818507, 10.81995957, 10.35060484,
        10.82970734, 10.46323527, 10.32227353, 10.44831145, 10.83305571],
       [10.00731276, 10.47727155, 10.81572745, 10.93915316, 10.30892678,
        10.6533983 , 10.37823214, 10.22721625, 10.94567981, 10.84548707],
       [10.83454918, 10.59649341, 10.79014112, 10.46593649, 10.3621356 ,
        10.8649656 , 10.72665958, 10.06282294, 10.36523932, 10.98355808],
       [10.7662607 , 10.61106074, 10.61188846, 10.98941861, 10.52545861,
        10.56110447, 10.23778176, 10.73713815, 10.6909835 , 10.70079236],
       [10.87581321, 10.33501248, 10.62943106, 10.77447654, 10.78880335,
        10.92721142, 10.83887853, 10.31346104, 10.05256299, 10.15068996],
       [10.06310261, 10.74676515, 10.25485637, 10.55354778, 10.90621103,
        10.03757763, 10.01284579, 10.38834101

In [10]:
b = np.zeros((10,10))

In [11]:
for x in range(10):
    for y in range(10):
        b[x][y] = b[x][y] + 10

In [12]:
b


array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [13]:
start1 = time.time()

In [14]:
a = a + b

In [15]:
end1 = time.time()

In [16]:
time_taken1  = end1- start1
time_taken1

0.050050973892211914

time_taken1 < time_taken

In [17]:
a


array([[20.47949963, 20.7299345 , 20.90773463, 20.84141837, 20.867988  ,
        20.31235114, 20.90253769, 20.36608185, 20.7321836 , 20.57726822],
       [20.21516325, 20.57756153, 20.89818507, 20.81995957, 20.35060484,
        20.82970734, 20.46323527, 20.32227353, 20.44831145, 20.83305571],
       [20.00731276, 20.47727155, 20.81572745, 20.93915316, 20.30892678,
        20.6533983 , 20.37823214, 20.22721625, 20.94567981, 20.84548707],
       [20.83454918, 20.59649341, 20.79014112, 20.46593649, 20.3621356 ,
        20.8649656 , 20.72665958, 20.06282294, 20.36523932, 20.98355808],
       [20.7662607 , 20.61106074, 20.61188846, 20.98941861, 20.52545861,
        20.56110447, 20.23778176, 20.73713815, 20.6909835 , 20.70079236],
       [20.87581321, 20.33501248, 20.62943106, 20.77447654, 20.78880335,
        20.92721142, 20.83887853, 20.31346104, 20.05256299, 20.15068996],
       [20.06310261, 20.74676515, 20.25485637, 20.55354778, 20.90621103,
        20.03757763, 20.01284579, 20.38834101

## Pandas

In [18]:
data = [[21, 'Ram', 'Maths', 20, 100],[22, 'Rom', 'Eng', 20, 90],[25, 'Tam', 'Bio', 20, 96],[27, 'Kam', 'Maths', 21, 99],[39, 'Sam', 'Bio', 22, 98],[32, 'Lam', 'Maths', 25, 100],[29, 'Tom', 'Maths', 25, 90],[30 ,'Pam', 'Eng', 27, 99],[58, 'Bam', 'Maths', 25, 80],[45, 'Jam', 'Bio', 25, 99]]

In [19]:
d = pd.DataFrame(data, columns=['rollno', 'name', 'subject', 'age', 'marks'])
d


rollno name subject  age  marks
0      21  Ram   Maths   20    100
1      22  Rom     Eng   20     90
2      25  Tam     Bio   20     96
3      27  Kam   Maths   21     99
4      39  Sam     Bio   22     98
5      32  Lam   Maths   25    100
6      29  Tom   Maths   25     90
7      30  Pam     Eng   27     99
8      58  Bam   Maths   25     80
9      45  Jam     Bio   25     99

In [20]:
sumn =  d.marks.sum()

In [21]:
sumn

951

In [22]:
mean = d.marks.mean()

In [23]:
mean

95.1

In [24]:
max = d.marks.max()

In [25]:
max

100

In [26]:
min = d.marks.min()

In [27]:
min

80

sd = d.marks.std()

In [28]:
sd = d.marks.std()

In [29]:
sd

6.5226102477799826

In [30]:
median = d.marks.median()

In [31]:
median

98.5

## Sum

In [32]:
sum1 = 5+6+7+8+9

In [33]:
sum1

35

In [34]:
list = [5,6,7,8,9]

In [35]:
sum2 = sum(list)

In [36]:
sum2

35

## Strings

In [37]:
str1 = input("Enter string1 ")

Enter string1 yay


In [38]:
str2 = input("Enter string2 ")

Enter string2 yay


In [39]:
if(len(str1)==len(str2)):
    str1 = sorted(str1)
    str2 = sorted(str2)
    if(str1 == str2):
        print("Anagram")
    else:
        print("Not an Anagram")
else:
    print("Not Anagram")
    
    

Anagram


## Rnadint

In [40]:
l1 = []

In [41]:
l1.append(np.random.randint(5,9))

In [42]:
for x in range(9):
    l1.append(np.random.randint(5,9))

In [43]:
l1

[7, 7, 8, 8, 7, 5, 6, 8, 5, 6]

In [44]:
np.unique(l1)

array([5, 6, 7, 8])

In [45]:
pd.value_counts(l1)

7    3
8    3
5    2
6    2
dtype: int64

In [46]:
l2 = pd.DataFrame(pd.value_counts(l1).reset_index())

In [47]:
l2.columns


Index(['index', 0], dtype='object')

In [48]:
l2.columns = ['data', 'count']

In [49]:
l2.columns

Index(['data', 'count'], dtype='object')

In [50]:
l2

data  count
0     7      3
1     8      3
2     5      2
3     6      2

In [51]:
np.max(l2['count'])

3

In [52]:
l2.data[0]

7

## List

In [53]:
l2 = []

In [54]:
l3 = []

In [55]:
for x in range(10):
    l2.append(np.random.randint(40,49))

In [56]:
for x in range(10):
    l3.append(np.random.randint(41,48))

In [57]:
l4 = []

In [58]:
y = 0
z = 0
for x in range(10):
    if(x%2==0):
        l4.append(l2[y])
        y=y+1
    else:
        l4.append(l3[z])
        z=z+1

In [59]:
l4

[42, 47, 43, 47, 43, 41, 44, 46, 45, 43]

In [60]:
def listunique(l):
    l2 = []
    l2 = pd.unique(l)
    return l2

In [61]:
listunique(l4)

array([42, 47, 43, 41, 44, 46, 45])

In [62]:
arr = np.random.random((20,5))

In [63]:
df = pd.DataFrame(arr)

In [64]:
df

0         1         2         3         4
0   0.169036  0.604225  0.974579  0.340194  0.821884
1   0.467662  0.731890  0.875850  0.562026  0.962575
2   0.379170  0.172032  0.401844  0.285978  0.736278
3   0.481863  0.894420  0.204522  0.298507  0.438222
4   0.095290  0.379279  0.689071  0.757711  0.474623
5   0.912176  0.080567  0.330251  0.450467  0.361352
6   0.768772  0.075066  0.960665  0.680530  0.218190
7   0.081634  0.773598  0.449748  0.248598  0.756895
8   0.375988  0.920646  0.546160  0.592725  0.252656
9   0.540385  0.273475  0.788138  0.745048  0.025959
10  0.654807  0.880676  0.118057  0.694154  0.703018
11  0.630330  0.893980  0.229399  0.392713  0.030741
12  0.329964  0.787496  0.307025  0.398446  0.688082
13  0.705315  0.294342  0.029271  0.565789  0.462181
14  0.120313  0.350359  0.418183  0.350483  0.347565
15  0.737518  0.260163  0.943404  0.033083  0.488041
16  0.812742  0.432322  0.772308  0.279239  0.303492
17  0.509145  0.236081  0.567214  0.938516  0.793045
18  0.436958  0.093294  0.425973  0.366804  0.258622
19  0.541438  0.047158  0.304378  0.293191  0.629110

In [65]:
brr = df.head(10)

In [66]:
brr

0         1         2         3         4
0  0.169036  0.604225  0.974579  0.340194  0.821884
1  0.467662  0.731890  0.875850  0.562026  0.962575
2  0.379170  0.172032  0.401844  0.285978  0.736278
3  0.481863  0.894420  0.204522  0.298507  0.438222
4  0.095290  0.379279  0.689071  0.757711  0.474623
5  0.912176  0.080567  0.330251  0.450467  0.361352
6  0.768772  0.075066  0.960665  0.680530  0.218190
7  0.081634  0.773598  0.449748  0.248598  0.756895
8  0.375988  0.920646  0.546160  0.592725  0.252656
9  0.540385  0.273475  0.788138  0.745048  0.025959

In [67]:
s = "-100#^sdfkj8902w3ir021@swf-20"

In [68]:
t = np.array([ 5, 16, 62, 23, 7, 12, 18, 3, 1])

In [69]:
ro = t[4:]

In [70]:
ro

array([ 7, 12, 18,  3,  1])

In [71]:
p = np . append(ro,t[0:4])

In [72]:
p

array([ 7, 12, 18,  3,  1,  5, 16, 62, 23])

## Transpose and Flatten

In [94]:
n = int(input("Enter number of rows: "))
m = int(input("Enter number of columns: "))

matrix = np.zeros((n,m))

for i in range (n):
    for j in range (m):
        matrix[i][j] = int(input())
        
for i in range(n):
    for j in range(m):
        print(matrix[i][j],end = " ")
    print()
    
        

Enter number of rows: 5
Enter number of columns: 2
1
2
3
4
5
6
7
8
9
9
1.0 2.0 
3.0 4.0 
5.0 6.0 
7.0 8.0 
9.0 9.0 


In [95]:
matrixT = np.transpose(matrix)

In [96]:
matrixT


array([[1., 3., 5., 7., 9.],
       [2., 4., 6., 8., 9.]])

In [97]:
matrix.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 9.])