<a href="https://colab.research.google.com/github/tiwaripari/ML/blob/main/MusicFeatures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:

import librosa
import librosa.display
import IPython.display as ipd
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
ipd.Audio('/content/drive/MyDrive/TunePocket-Rock-Party-30-Sec-Intro-Preview.mp3')

In [ ]:
def feature_extraction(file_path):
  # Load the audio file
  x, sample_rate = librosa.load(file_path)
  #extract feature from audio
  mfcc = []
  mfcc = np.mean(librosa.feature.mfcc(y=x, sr=sample_rate, n_mfcc=13).T, axis=0)
  return mfcc

In [ ]:
mfcc = feature_extraction('/content/drive/MyDrive/TunePocket-Rock-Party-30-Sec-Intro-Preview.mp3')

In [ ]:
mfcc

array([-22.972054 ,  84.601036 , -28.321905 ,  32.63283  ,  -1.4422629,
         5.140584 ,   1.2359622,   6.829946 ,   1.3748925,   7.0407195,
        -1.3476068,   5.826765 ,  -1.3939185], dtype=float32)

In [ ]:
features = {}
for i in range(1, 14):
        features[f'_MFCC_Mean_{i}'] = mfcc[i-1].mean()
features

{'_MFCC_Mean_1': -22.972054,
 '_MFCC_Mean_2': 84.601036,
 '_MFCC_Mean_3': -28.321905,
 '_MFCC_Mean_4': 32.63283,
 '_MFCC_Mean_5': -1.4422629,
 '_MFCC_Mean_6': 5.140584,
 '_MFCC_Mean_7': 1.2359622,
 '_MFCC_Mean_8': 6.829946,
 '_MFCC_Mean_9': 1.3748925,
 '_MFCC_Mean_10': 7.0407195,
 '_MFCC_Mean_11': -1.3476068,
 '_MFCC_Mean_12': 5.826765,
 '_MFCC_Mean_13': -1.3939185}

In [ ]:
x, sample_rate = librosa.load('/content/drive/MyDrive/TunePocket-Rock-Party-30-Sec-Intro-Preview.mp3')
chroma = np.mean(librosa.feature.chroma_stft(y=x, sr=sample_rate).T,axis=0)


In [ ]:
chroma


array([0.45105198, 0.40799463, 0.49941653, 0.77754074, 0.49573925,
       0.40501738, 0.4624765 , 0.57066023, 0.74407774, 0.5218353 ,
       0.39746425, 0.34780678], dtype=float32)

In [ ]:
for i in range(1, 13):
        features[f'_Chromagram_Mean_{i}'] = chroma[i-1]
features

{'_MFCC_Mean_1': -22.972054,
 '_MFCC_Mean_2': 84.601036,
 '_MFCC_Mean_3': -28.321905,
 '_MFCC_Mean_4': 32.63283,
 '_MFCC_Mean_5': -1.4422629,
 '_MFCC_Mean_6': 5.140584,
 '_MFCC_Mean_7': 1.2359622,
 '_MFCC_Mean_8': 6.829946,
 '_MFCC_Mean_9': 1.3748925,
 '_MFCC_Mean_10': 7.0407195,
 '_MFCC_Mean_11': -1.3476068,
 '_MFCC_Mean_12': 5.826765,
 '_MFCC_Mean_13': -1.3939185,
 '_Chromagram_Mean_1': 0.45105198,
 '_Chromagram_Mean_2': 0.40799463,
 '_Chromagram_Mean_3': 0.49941653,
 '_Chromagram_Mean_4': 0.77754074,
 '_Chromagram_Mean_5': 0.49573925,
 '_Chromagram_Mean_6': 0.40501738,
 '_Chromagram_Mean_7': 0.4624765,
 '_Chromagram_Mean_8': 0.57066023,
 '_Chromagram_Mean_9': 0.74407774,
 '_Chromagram_Mean_10': 0.5218353,
 '_Chromagram_Mean_11': 0.39746425,
 '_Chromagram_Mean_12': 0.34780678}

In [ ]:
harmonic = librosa.effects.harmonic(x)

In [ ]:
harmonic

array([-3.3690006e-02, -4.1169461e-02, -4.0682379e-02, ...,
        7.8576306e-08,  1.9876099e-09, -2.2530838e-08], dtype=float32)

In [ ]:
harmonic.shape

(793800,)

In [ ]:
features['_HarmonicChangeDetectionFunction_Mean'] = np.mean(librosa.effects.harmonic(x))

In [ ]:
features

{'_MFCC_Mean_1': -22.972054,
 '_MFCC_Mean_2': 84.601036,
 '_MFCC_Mean_3': -28.321905,
 '_MFCC_Mean_4': 32.63283,
 '_MFCC_Mean_5': -1.4422629,
 '_MFCC_Mean_6': 5.140584,
 '_MFCC_Mean_7': 1.2359622,
 '_MFCC_Mean_8': 6.829946,
 '_MFCC_Mean_9': 1.3748925,
 '_MFCC_Mean_10': 7.0407195,
 '_MFCC_Mean_11': -1.3476068,
 '_MFCC_Mean_12': 5.826765,
 '_MFCC_Mean_13': -1.3939185,
 '_Chromagram_Mean_1': 0.45105198,
 '_Chromagram_Mean_2': 0.40799463,
 '_Chromagram_Mean_3': 0.49941653,
 '_Chromagram_Mean_4': 0.77754074,
 '_Chromagram_Mean_5': 0.49573925,
 '_Chromagram_Mean_6': 0.40501738,
 '_Chromagram_Mean_7': 0.4624765,
 '_Chromagram_Mean_8': 0.57066023,
 '_Chromagram_Mean_9': 0.74407774,
 '_Chromagram_Mean_10': 0.5218353,
 '_Chromagram_Mean_11': 0.39746425,
 '_Chromagram_Mean_12': 0.34780678,
 '_HarmonicChangeDetectionFunction_Mean': -5.5750104e-07}

In [ ]:
spectrogram = librosa.stft(x)
power_spectrogram = np.abs(spectrogram) ** 2

In [99]:
features['_HarmonicChangeDetectionFunction_Mean'] = librosa.feature.delta(power_spectrogram, order=1, axis=-1).mean()
features['_HarmonicChangeDetectionFunction_Std'] = librosa.feature.delta(power_spectrogram, order=1,axis=-1).std()
features['_HarmonicChangeDetectionFunction_Slope'] = np.mean(librosa.feature.delta(power_spectrogram, order=1, axis=-1))
# features['_HarmonicChangeDetectionFunction_PeriodFreq'], features['_HarmonicChangeDetectionFunction_PeriodAmp'] = librosa.periodicity(power_spectrogram,sr=sr)
# features['_HarmonicChangeDetectionFunction_PeriodEntropy'] = librosa.periodicity_entropy(power_spectrogram,sr=sample_rate)


In [100]:
features

{'_MFCC_Mean_1': -22.972054,
 '_MFCC_Mean_2': 84.601036,
 '_MFCC_Mean_3': -28.321905,
 '_MFCC_Mean_4': 32.63283,
 '_MFCC_Mean_5': -1.4422629,
 '_MFCC_Mean_6': 5.140584,
 '_MFCC_Mean_7': 1.2359622,
 '_MFCC_Mean_8': 6.829946,
 '_MFCC_Mean_9': 1.3748925,
 '_MFCC_Mean_10': 7.0407195,
 '_MFCC_Mean_11': -1.3476068,
 '_MFCC_Mean_12': 5.826765,
 '_MFCC_Mean_13': -1.3939185,
 '_Chromagram_Mean_1': 0.45105198,
 '_Chromagram_Mean_2': 0.40799463,
 '_Chromagram_Mean_3': 0.49941653,
 '_Chromagram_Mean_4': 0.77754074,
 '_Chromagram_Mean_5': 0.49573925,
 '_Chromagram_Mean_6': 0.40501738,
 '_Chromagram_Mean_7': 0.4624765,
 '_Chromagram_Mean_8': 0.57066023,
 '_Chromagram_Mean_9': 0.74407774,
 '_Chromagram_Mean_10': 0.5218353,
 '_Chromagram_Mean_11': 0.39746425,
 '_Chromagram_Mean_12': 0.34780678,
 '_HarmonicChangeDetectionFunction_Mean': -0.011699124,
 '_HarmonicChangeDetectionFunction_Std': 75.90025,
 '_HarmonicChangeDetectionFunction_Slope': -0.011699124,
 '_RMSenergy_Mean': 0.24375623,
 '_Lowenergy_M

In [104]:
features['_RMSenergy_Mean'] = librosa.feature.rms(y=x).mean()
features['_Lowenergy_Mean'] = librosa.feature.spectral_contrast(S=power_spectrogram).mean()
features['_Fluctuation_Mean'] = librosa.feature.spectral_flatness(S=power_spectrogram).mean()
features['_Tempo_Mean'] = librosa.feature.rhythm.tempo(y=x, sr=sample_rate)[0].mean()

In [105]:
features


{'_MFCC_Mean_1': -22.972054,
 '_MFCC_Mean_2': 84.601036,
 '_MFCC_Mean_3': -28.321905,
 '_MFCC_Mean_4': 32.63283,
 '_MFCC_Mean_5': -1.4422629,
 '_MFCC_Mean_6': 5.140584,
 '_MFCC_Mean_7': 1.2359622,
 '_MFCC_Mean_8': 6.829946,
 '_MFCC_Mean_9': 1.3748925,
 '_MFCC_Mean_10': 7.0407195,
 '_MFCC_Mean_11': -1.3476068,
 '_MFCC_Mean_12': 5.826765,
 '_MFCC_Mean_13': -1.3939185,
 '_Chromagram_Mean_1': 0.45105198,
 '_Chromagram_Mean_2': 0.40799463,
 '_Chromagram_Mean_3': 0.49941653,
 '_Chromagram_Mean_4': 0.77754074,
 '_Chromagram_Mean_5': 0.49573925,
 '_Chromagram_Mean_6': 0.40501738,
 '_Chromagram_Mean_7': 0.4624765,
 '_Chromagram_Mean_8': 0.57066023,
 '_Chromagram_Mean_9': 0.74407774,
 '_Chromagram_Mean_10': 0.5218353,
 '_Chromagram_Mean_11': 0.39746425,
 '_Chromagram_Mean_12': 0.34780678,
 '_HarmonicChangeDetectionFunction_Mean': -0.011699124,
 '_HarmonicChangeDetectionFunction_Std': 75.90025,
 '_HarmonicChangeDetectionFunction_Slope': -0.011699124,
 '_RMSenergy_Mean': 0.24375623,
 '_Lowenergy_M