<a href="https://colab.research.google.com/github/tiwaripari/ML/blob/main/RandomForestEmotionClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import librosa
import librosa.display
import IPython.display as ipd
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv("/content/drive/MyDrive/Acoustic Features.csv") 

In [4]:
df


Class  _RMSenergy_Mean  _Lowenergy_Mean  _Fluctuation_Mean  _Tempo_Mean  \
0    relax            0.052            0.591              9.136      130.043   
1    relax            0.125            0.439              6.680      142.240   
2    relax            0.046            0.639             10.578      188.154   
3    relax            0.135            0.603             10.442       65.991   
4    relax            0.066            0.591              9.769       88.890   
..     ...              ...              ...                ...          ...   
395  angry            0.174            0.578              5.265      161.144   
396  angry            0.176            0.498              5.042      179.787   
397  angry            0.187            0.557              4.724      134.032   
398  angry            0.140            0.573              4.470      113.600   
399  angry            0.086            0.475              5.343      151.748   

     _MFCC_Mean_1  _MFCC_Mean_2  _MFCC_Mean_3  _MFCC_Mean_4  _MFCC_Mean_5  \
0           3.997         0.363         0.887         0.078         0.221   
1           4.058         0.516         0.785         0.397         0.556   
2           2.775         0.903         0.502         0.329         0.287   
3           2.841         1.552         0.612         0.351         0.011   
4           3.217         0.228         0.814         0.096         0.434   
..            ...           ...           ...           ...           ...   
395         2.985         0.065         0.718         0.046         0.265   
396         2.790        -0.148         0.342        -0.011         0.029   
397         1.672         0.566         0.880        -0.113         0.244   
398         1.997        -0.210         0.694         0.089         0.206   
399         2.240        -0.014         0.834        -0.021         0.345   

     ...  _Chromagram_Mean_9  _Chromagram_Mean_10  _Chromagram_Mean_11  \
0    ...               0.426                1.000                0.008   
1    ...               0.002                1.000                0.000   
2    ...               0.184                0.746                0.016   
3    ...               0.038                1.000                0.161   
4    ...               0.004                0.404                1.000   
..   ...                 ...                  ...                  ...   
395  ...               0.374                0.838                0.413   
396  ...               0.020                1.000                0.640   
397  ...               0.052                0.184                0.287   
398  ...               0.137                1.000                0.304   
399  ...               0.099                1.000                0.094   

     _Chromagram_Mean_12  _HarmonicChangeDetectionFunction_Mean  \
0                  0.101                                  0.316   
1                  0.984                                  0.285   
2                  1.000                                  0.413   
3                  0.757                                  0.422   
4                  0.001                                  0.345   
..                   ...                                    ...   
395                0.125                                  0.323   
396                0.010                                  0.233   
397                0.101                                  0.269   
398                0.140                                  0.277   
399                0.033                                  0.195   

     _HarmonicChangeDetectionFunction_Std  \
0                                   0.261   
1                                   0.211   
2                                   0.299   
3                                   0.265   
4                                   0.261   
..                                    ...   
395                                 0.140   
396                                 0.127   
397                 

In [5]:
df.Class.value_counts()

relax    100
happy    100
sad      100
angry    100
Name: Class, dtype: int64

In [6]:
features = df.columns[1:]
features

Index(['_RMSenergy_Mean', '_Lowenergy_Mean', '_Fluctuation_Mean',
       '_Tempo_Mean', '_MFCC_Mean_1', '_MFCC_Mean_2', '_MFCC_Mean_3',
       '_MFCC_Mean_4', '_MFCC_Mean_5', '_MFCC_Mean_6', '_MFCC_Mean_7',
       '_MFCC_Mean_8', '_MFCC_Mean_9', '_MFCC_Mean_10', '_MFCC_Mean_11',
       '_MFCC_Mean_12', '_MFCC_Mean_13', '_Roughness_Mean', '_Roughness_Slope',
       '_Zero-crossingrate_Mean', '_AttackTime_Mean', '_AttackTime_Slope',
       '_Rolloff_Mean', '_Eventdensity_Mean', '_Pulseclarity_Mean',
       '_Brightness_Mean', '_Spectralcentroid_Mean', '_Spectralspread_Mean',
       '_Spectralskewness_Mean', '_Spectralkurtosis_Mean',
       '_Spectralflatness_Mean', '_EntropyofSpectrum_Mean',
       '_Chromagram_Mean_1', '_Chromagram_Mean_2', '_Chromagram_Mean_3',
       '_Chromagram_Mean_4', '_Chromagram_Mean_5', '_Chromagram_Mean_6',
       '_Chromagram_Mean_7', '_Chromagram_Mean_8', '_Chromagram_Mean_9',
       '_Chromagram_Mean_10', '_Chromagram_Mean_11', '_Chromagram_Mean_12',
      

In [7]:
#Creating Test and Train data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
#View top 10 rows
df.head(10)

Class  _RMSenergy_Mean  _Lowenergy_Mean  _Fluctuation_Mean  _Tempo_Mean  \
0  relax            0.052            0.591              9.136      130.043   
1  relax            0.125            0.439              6.680      142.240   
2  relax            0.046            0.639             10.578      188.154   
3  relax            0.135            0.603             10.442       65.991   
4  relax            0.066            0.591              9.769       88.890   
5  relax            0.137            0.510              7.664      116.044   
6  relax            0.123            0.533              7.483      136.444   
7  relax            0.103            0.575              7.006      141.132   
8  relax            0.145            0.542              6.846       82.048   
9  relax            0.129            0.618              8.668       93.020   

   _MFCC_Mean_1  _MFCC_Mean_2  _MFCC_Mean_3  _MFCC_Mean_4  _MFCC_Mean_5  ...  \
0         3.997         0.363         0.887         0.078         0.221  ...   
1         4.058         0.516         0.785         0.397         0.556  ...   
2         2.775         0.903         0.502         0.329         0.287  ...   
3         2.841         1.552         0.612         0.351         0.011  ...   
4         3.217         0.228         0.814         0.096         0.434  ...   
5         2.313        -0.082         0.365         0.033        -0.136  ...   
6         4.572         1.171         0.939         0.358         0.024  ...   
7         3.495         0.553         0.275         0.269         0.257  ...   
8         4.010         0.550         0.568         0.559         0.218  ...   
9         2.318         0.744         0.537        -0.116         0.119  ...   

   _Chromagram_Mean_10  _Chromagram_Mean_11  _Chromagram_Mean_12  \
0                1.000                0.008                0.101   
1                1.000                0.000                0.984   
2                0.746                0.016                1.000   
3                1.000                0.161                0.757   
4                0.404                1.000                0.001   
5                0.391                0.102                0.000   
6                1.000                0.000                0.143   
7                1.000                0.030                0.746   
8                0.150                0.910                0.000   
9                0.018                0.385                0.000   

   _HarmonicChangeDetectionFunction_Mean  \
0                                  0.316   
1                                  0.285   
2                                  0.413   
3                                  0.422   
4                                  0.345   
5                                  0.280   
6                                  0.210   
7                                  0.366   
8                                  0.322   
9                                  0.388   

   _HarmonicChangeDetectionFunction_Std  \
0                                 0.261   
1                                 0.211   
2                                 0.299   
3                                 0.265   
4                                 0.261   
5                                 0.240   
6                                 0.174   
7                                 0.267   
8                                 0.210   
9                                 0.340   

   _HarmonicChangeDetectionFunction_Slope  \
0                                   0.018   
1                                  -0.082   
2                                   0.134   
3                                   0.042   
4                                   0.089   
5                                   0.355   
6                                   0.193   
7                                  -0.061   
8                                   0.031   
9                                   0.122   

   _HarmonicChangeDetectionFunction_PeriodFreq  \
0        

In [8]:
#Create dataframes with train and test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

#show the number of rows in test and train dataframe
print("training data ", len(train))
print("testing data ", len(test))

training data  314
testing data  86


In [9]:
#Converting each Class naem into digits
y = pd.factorize(train['Class'])[0]
#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [10]:
#Converting each Class name into digits for test data
x = pd.factorize(test['Class'])[0]
#viewing target
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
target_names = (train['Class']).unique()
target_names


array(['relax', 'happy', 'sad', 'angry'], dtype=object)

In [12]:
#Creating Random Forest Classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y)


RandomForestClassifier(n_jobs=2, random_state=0)

In [13]:
#Applying trained Classifier to the test
predictions = clf.predict(test[features])
predictions

array([0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2,
       2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 1, 3, 3])

In [14]:
#viewing predicted probablities of first 10 observation
clf.predict_proba(test[features])[:10]

array([[0.59, 0.06, 0.32, 0.03],
       [0.7 , 0.02, 0.24, 0.04],
       [0.83, 0.01, 0.08, 0.08],
       [0.59, 0.03, 0.28, 0.1 ],
       [0.6 , 0.  , 0.36, 0.04],
       [0.65, 0.02, 0.27, 0.06],
       [0.53, 0.03, 0.3 , 0.14],
       [0.25, 0.02, 0.33, 0.4 ],
       [0.71, 0.  , 0.26, 0.03],
       [0.65, 0.04, 0.23, 0.08]])

In [15]:
#mapping names of moods for each music for each predicted mood
preds  = target_names[clf.predict(test[features])]

#View the predicted moods for firat five observations
preds[10:20]

array(['relax', 'relax', 'relax', 'sad', 'relax', 'relax', 'relax',
       'relax', 'sad', 'relax'], dtype=object)

In [16]:
#Viewing Actual mood of test music or data
test['Class'].head()

2     relax
3     relax
8     relax
12    relax
18    relax
Name: Class, dtype: object

In [17]:
#Creating confusion matrix
#crosstab takes two sets of data and forms chart out of it
pd.crosstab(test['Class'], preds, rownames=['Actual mood'], colnames=['Predicted Species'])

Predicted Species  angry  happy  relax  sad
Actual mood                                
angry                 11      1      0    2
happy                  0     18      0    3
relax                  1      0     20    4
sad                    1      2      3   20

In [18]:
accuracy = accuracy_score(x, predictions) 

In [19]:
accuracy * 100

80.23255813953489

In [21]:
from google.colab import files

# Prompt the user to upload a file
uploaded = files.upload()


Saving finalmusicfeatureextractednew.py to finalmusicfeatureextractednew.py


In [22]:
from finalmusicfeatureextractednew import feature_extraction

In [85]:
# x = '/content/drive/MyDrive/TunePocket-Rock-Party-30-Sec-Intro-Preview (1).mp3'
# features = {}
# features = feature_extraction(x)

In [86]:
# features.columns

In [81]:
def at_avg():
  attribute_avg = train['_HarmonicChangeDetectionFunction_PeriodEntropy'].mean()
  return attribute_avg


In [87]:
# features['_HarmonicChangeDetectionFunction_PeriodEntropy'] = at_avg()

In [72]:
def predict_emotion(audio_file, attribute_avg):
  x = audio_file
  features = {}
  features = feature_extraction(x)
  features['_HarmonicChangeDetectionFunction_PeriodEntropy'] = attribute_avg
  prediction = target_names[clf.predict(features)][0]
  return prediction

In [88]:
# audio_file = '/content/drive/MyDrive/Happiness.mp3'
# predict_emotion(audio_file, at_avg())

In [89]:
# y = '/content/drive/MyDrive/Happiness.mp3'
# features_2 = {}
# features_2 = feature_extraction(y)

In [90]:

# features_2

In [91]:
# features_2['_HarmonicChangeDetectionFunction_PeriodEntropy'] = attribute_avg

In [92]:
# prediction3 = target_names[clf.predict(features_2)]
# prediction3

In [93]:
# z = '/content/Energetic.mp3'
# features_3 = {}
# features_3 = feature_extraction(z)

In [94]:
# features_3['_HarmonicChangeDetectionFunction_PeriodEntropy'] = attribute_avg

In [95]:
# prediction4 = target_names[clf.predict(features_3)]
# prediction4